//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchange.TestClient.CurrencyServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyRate", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service")]
    [System.SerializableAttribute()]
    public partial class CurrencyRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mid {
            get {
                return this.MidField;
            }
            set {
                if ((this.MidField.Equals(value) != true)) {
                    this.MidField = value;
                    this.RaisePropertyChanged("Mid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PlnValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PlnValue {
            get {
                return this.PlnValueField;
            }
            set {
                if ((this.PlnValueField.Equals(value) != true)) {
                    this.PlnValueField = value;
                    this.RaisePropertyChanged("PlnValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoricalRate", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service")]
    [System.SerializableAttribute()]
    public partial class HistoricalRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyServiceRef.ICurrencyService")]
    public interface ICurrencyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/HelloWorld", ReplyAction="http://tempuri.org/ICurrencyService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/HelloWorld", ReplyAction="http://tempuri.org/ICurrencyService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetExchangeRate", ReplyAction="http://tempuri.org/ICurrencyService/GetExchangeRateResponse")]
        double GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetExchangeRate", ReplyAction="http://tempuri.org/ICurrencyService/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetAllRates", ReplyAction="http://tempuri.org/ICurrencyService/GetAllRatesResponse")]
        CurrencyExchange.TestClient.CurrencyServiceRef.CurrencyRate[] GetAllRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetAllRates", ReplyAction="http://tempuri.org/ICurrencyService/GetAllRatesResponse")]
        System.Threading.Tasks.Task<CurrencyExchange.TestClient.CurrencyServiceRef.CurrencyRate[]> GetAllRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/RegisterUser", ReplyAction="http://tempuri.org/ICurrencyService/RegisterUserResponse")]
        string RegisterUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/RegisterUser", ReplyAction="http://tempuri.org/ICurrencyService/RegisterUserResponse")]
        System.Threading.Tasks.Task<string> RegisterUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/Login", ReplyAction="http://tempuri.org/ICurrencyService/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/Login", ReplyAction="http://tempuri.org/ICurrencyService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetUserBalance", ReplyAction="http://tempuri.org/ICurrencyService/GetUserBalanceResponse")]
        double GetUserBalance(string username, string currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetUserBalance", ReplyAction="http://tempuri.org/ICurrencyService/GetUserBalanceResponse")]
        System.Threading.Tasks.Task<double> GetUserBalanceAsync(string username, string currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/TopUpAccount", ReplyAction="http://tempuri.org/ICurrencyService/TopUpAccountResponse")]
        bool TopUpAccount(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/TopUpAccount", ReplyAction="http://tempuri.org/ICurrencyService/TopUpAccountResponse")]
        System.Threading.Tasks.Task<bool> TopUpAccountAsync(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/BuyCurrency", ReplyAction="http://tempuri.org/ICurrencyService/BuyCurrencyResponse")]
        string BuyCurrency(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/BuyCurrency", ReplyAction="http://tempuri.org/ICurrencyService/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<string> BuyCurrencyAsync(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/SellCurrency", ReplyAction="http://tempuri.org/ICurrencyService/SellCurrencyResponse")]
        string SellCurrency(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/SellCurrency", ReplyAction="http://tempuri.org/ICurrencyService/SellCurrencyResponse")]
        System.Threading.Tasks.Task<string> SellCurrencyAsync(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetUserTransactions", ReplyAction="http://tempuri.org/ICurrencyService/GetUserTransactionsResponse")]
        CurrencyExchange.TestClient.CurrencyServiceRef.Transaction[] GetUserTransactions(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetUserTransactions", ReplyAction="http://tempuri.org/ICurrencyService/GetUserTransactionsResponse")]
        System.Threading.Tasks.Task<CurrencyExchange.TestClient.CurrencyServiceRef.Transaction[]> GetUserTransactionsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetHistoricalRates", ReplyAction="http://tempuri.org/ICurrencyService/GetHistoricalRatesResponse")]
        CurrencyExchange.TestClient.CurrencyServiceRef.HistoricalRate[] GetHistoricalRates(string currencyCode, string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetHistoricalRates", ReplyAction="http://tempuri.org/ICurrencyService/GetHistoricalRatesResponse")]
        System.Threading.Tasks.Task<CurrencyExchange.TestClient.CurrencyServiceRef.HistoricalRate[]> GetHistoricalRatesAsync(string currencyCode, string startDate, string endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyServiceChannel : CurrencyExchange.TestClient.CurrencyServiceRef.ICurrencyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyServiceClient : System.ServiceModel.ClientBase<CurrencyExchange.TestClient.CurrencyServiceRef.ICurrencyService>, CurrencyExchange.TestClient.CurrencyServiceRef.ICurrencyService {
        
        public CurrencyServiceClient() {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public double GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public CurrencyExchange.TestClient.CurrencyServiceRef.CurrencyRate[] GetAllRates() {
            return base.Channel.GetAllRates();
        }
        
        public System.Threading.Tasks.Task<CurrencyExchange.TestClient.CurrencyServiceRef.CurrencyRate[]> GetAllRatesAsync() {
            return base.Channel.GetAllRatesAsync();
        }
        
        public string RegisterUser(string username, string password) {
            return base.Channel.RegisterUser(username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUserAsync(string username, string password) {
            return base.Channel.RegisterUserAsync(username, password);
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public double GetUserBalance(string username, string currency) {
            return base.Channel.GetUserBalance(username, currency);
        }
        
        public System.Threading.Tasks.Task<double> GetUserBalanceAsync(string username, string currency) {
            return base.Channel.GetUserBalanceAsync(username, currency);
        }
        
        public bool TopUpAccount(string username, double amount) {
            return base.Channel.TopUpAccount(username, amount);
        }
        
        public System.Threading.Tasks.Task<bool> TopUpAccountAsync(string username, double amount) {
            return base.Channel.TopUpAccountAsync(username, amount);
        }
        
        public string BuyCurrency(string username, string currencyCode, double amount) {
            return base.Channel.BuyCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> BuyCurrencyAsync(string username, string currencyCode, double amount) {
            return base.Channel.BuyCurrencyAsync(username, currencyCode, amount);
        }
        
        public string SellCurrency(string username, string currencyCode, double amount) {
            return base.Channel.SellCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> SellCurrencyAsync(string username, string currencyCode, double amount) {
            return base.Channel.SellCurrencyAsync(username, currencyCode, amount);
        }
        
        public CurrencyExchange.TestClient.CurrencyServiceRef.Transaction[] GetUserTransactions(string username) {
            return base.Channel.GetUserTransactions(username);
        }
        
        public System.Threading.Tasks.Task<CurrencyExchange.TestClient.CurrencyServiceRef.Transaction[]> GetUserTransactionsAsync(string username) {
            return base.Channel.GetUserTransactionsAsync(username);
        }
        
        public CurrencyExchange.TestClient.CurrencyServiceRef.HistoricalRate[] GetHistoricalRates(string currencyCode, string startDate, string endDate) {
            return base.Channel.GetHistoricalRates(currencyCode, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<CurrencyExchange.TestClient.CurrencyServiceRef.HistoricalRate[]> GetHistoricalRatesAsync(string currencyCode, string startDate, string endDate) {
            return base.Channel.GetHistoricalRatesAsync(currencyCode, startDate, endDate);
        }
    }
}
